feature: Dubbo api docs UI
apache/dubbo-admin pull request #671
Opened 2020-12-18 03:04 UTC by KeRan213539

feature: Dubbo api docs

2020-12-18 03:19 UTC, beiwei30 requested changes

2020-12-18 03:19 UTC, beiwei30 commented on dubbo-admin-server/pom.xml
> +            <version>${lombok.version}</version>
pls. don't use lombok

2020-12-18 03:19 UTC, beiwei30 commented on dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/ApiDocsController.java
> + * @author klw(213539@qq.com)
pls. remove author info.

2020-12-18 03:19 UTC, beiwei30 commented on dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/beans/DubboApiDocsParamInfoBean.java
> +package org.apache.dubbo.admin.controller.beans;
pls. add apache license header.

2020-12-18 03:19 UTC, beiwei30 commented on dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/beans/DubboApiDocsParamInfoBean.java
> + * @author klw(213539 @ qq.com)
again, pls. remove author info.

2020-12-18 03:19 UTC, beiwei30 commented on dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/editors/CustomLocalDateEditor.java
> + * @author klw(213539 @ qq.com)
pls. remove author info.

2020-12-18 03:19 UTC, beiwei30 commented on dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/editors/CustomLocalDateTimeEditor.java
> + * @author klw(213539 @ qq.com)
pls. remove author info.

2020-12-18 03:19 UTC, beiwei30 commented on dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/dto/docs/ApiInfoRequest.java
> + * @author klw(213539@qq.com)
pls. remove author info.

2020-12-18 03:19 UTC, beiwei30 commented on dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/dto/docs/CallDubboServiceRequest.java
> + * @author klw(213539@qq.com)
remove athor info.

2020-12-18 03:19 UTC, beiwei30 commented on dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/dto/docs/CallDubboServiceRequestInterfaceParam.java
> + * @author klw(213539@qq.com)
remove author info.

2020-12-18 03:19 UTC, beiwei30 commented on dubbo-admin-server/src/main/java/org/apache/dubbo/admin/utils/LocalDateTimeUtil.java
> + * @author klw(213539 @ qq.com)
remove author info.

2020-12-18 03:19 UTC, beiwei30 commented on dubbo-admin-server/src/main/resources/application-test.properties
> +admin.registry.address=nacos://127.0.0.1:8848
pls. rollback to zookeeper

2020-12-18 03:19 UTC, beiwei30 commented on dubbo-admin-server/src/main/resources/application.properties
> +admin.registry.address=nacos://127.0.0.1:8848
pls. rollback to zookeeper since I believe it's irrelevant to this PR

2020-12-21 08:04 UTC, beiwei30 approved these changes
LGTM.

2020-12-21 08:04 UTC, merged

2021-11-10 17:38 UTC, m7adf7d reviewed
m7adf7d-admin-backend/src/main/java/org/apache/m7adf7d/admin/service/impl/UserServiceImpl.java